packages:
  - projects/lin-compiler
  - projects/vscode-extension
  - projects/scripts

catalog:
  typescript: ^7.0.2

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - electron
  - electron-winstaller
  - esbuild
  - keytar
