// Hardcoded copy of workbench/linscript-exploration/e00_002_000.linscript (guinea pig for the Script Browser).
// String.raw keeps the literal \n sequences inside AutoText strings intact.
export const e00_002_000 = String.raw`ScreenFade(1, 0, 1)
ChangeUI(11, 1)
SetVar8(13, 32, 0)
ChangeUI(7, 0)
ChangeUI(16, 0)
SetVar16(0, 0, 0)
SetVar16(2, 0, 100)
SetVar16(3, 0, 100)
SetVar16(15, 0, 17)
SetVar16(8, 0, 0)
SetVar8(0, 12, 0)
ChangeUI(6, 0)
LoadMap(14, 0, 255)
ChangeUI(9, 0)
ObjectState(26, 0, 0, 0, 0)
Music(7, 100, 0)
ChangeUI(3, 0)
ChangeUI(2, 1)
ChangeUI(51, 0)
ChangeUI(6, 1)
ShowBackground(0, 1)
ChangeUI(9, 1)
ScreenFade(0, 1, 24)
ChangeUI(0, 0)
ChangeUI(1, 1)
Speaker(0)
AutoText("...\n")
AutoText("...\n")
AutoText("...\n")
AutoText("...Nng?\n")
ChangeUI(1, 0)
ScreenFade(1, 1, 24)
ShowBackground(0, 3)
Animation(741, 0, 0, 0, 0, 0, 3)
ScreenFade(0, 1, 24)
SetVar16(6, 0, 60)
Animation(741, 0, 0, 0, 0, 0, 1)
SetVar16(6, 0, 60)
ChangeUI(1, 1)
Speaker(0)
Voice(0, 99, 44, 100)
AutoText("Wh-What...?\n")
AutoText("Where am I?\n")
ChangeUI(0, 1)
Speaker(0)
AutoText("<CLT 4>I woke up with my head resting on top of a hard wooden\ndesk.\n<CLT>")
AutoText("<CLT 4>My body feels...heavy.\n<CLT>")
AutoText("<CLT 4>It's pretty normal for me to zonk off in the middle of\nsome boring class or whatever, but...\n<CLT>")
AutoText("<CLT 4>What was I doing asleep here just now?\n<CLT>")
AutoText("<CLT 4>This isn't a classroom I've ever been in before.\n<CLT>")
ChangeUI(0, 0)
Speaker(0)
AutoText("What the heck is going on...?\n")
ChangeUI(1, 0)
Music(255, 90, 0)
SetVar16(6, 0, 60)
ScreenFade(1, 1, 24)
Animation(741, 0, 0, 0, 0, 0, 255)
Music(32, 100, 60)
ChangeUI(6, 0)
ChangeUI(14, 1)
LoadMap(1, 1, 255)
SetVar16(6, 0, 30)
ChangeUI(27, 0)
ChangeUI(0, 1)
ChangeUI(2, 0)
ChangeUI(1, 1)
Speaker(31)
AutoText("<CLT 23>Welcome to Hope's Peak Academy! Firstly, we'd like to\nexplain the basic controls.\n<CLT>")
AutoText("<CLT 23>You can use the %CTRL_INVESTIGATE_AIM% to adjust your <CLT><CLT 3>aim<CLT><CLT 23>.\n<CLT>")
AutoText("<CLT 23>If you aim at an object you can interact with,\nyou can press the <CLT><CLT 3>%CTRL_INTERACT%<CLT><CLT 23>...\n<CLT>")
AutoText("<CLT 23>And presto! You'll <CLT><CLT 3>investigate<CLT><CLT 23> that object.\n<CLT>")
AutoText("<CLT 23>Use the <CLT><CLT 3>%CTRL_ADJUST_VIEW%<CLT><CLT 23>\nto <CLT 3>adjust your viewpoint<CLT>.\n<CLT>")
AutoText("<CLT 23>%CTRL_INVESTIGATE_VIEW_ALT%\n<CLT>")
AutoText("<CLT 23>Why don't you try looking around the classroom?\n<CLT>")
ChangeUI(1, 0)
ChangeUI(2, 1)
ChangeUI(16, 1)
Goto(500)
CheckCharacter(255)
CheckObject(20)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>There's a TV...\n<CLT>")
  AutoText("<CLT 4>The school *is* funded by the national government,\nso I guess it's not that weird to have TVs in here...\n<CLT>")
  AutoText("<CLT 4>Something feels...off. I wonder what it is...\n<CLT>")
  ChangeUI(1, 0)
CheckObject(21)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>Is that...a surveillance camera?\n<CLT>")
  AutoText("<CLT 4>It's a dangerous world we live in. I guess they have\nthese to keep weirdos from just wandering in.\n<CLT>")
  ChangeUI(1, 0)
CheckObject(22)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>Jeez, I can't believe it's already 8 o'clock.\n<CLT>")
  AutoText("<CLT 4>It was just after 7 when I first got here.\n<CLT>")
  AutoText("<CLT 4>Has it really been almost an hour since then...?\n<CLT>")
  ChangeUI(1, 0)
  SetVar8(13, 0, 1)
  EvaluateFlag(13, 0, 0, 1, 6, 13, 1, 0, 1, 6, 13, 2, 0, 1)
  IfTrue()
  Goto(501)
  Goto(0)
  Label(501)
CheckObject(23)
  ChangeUI(15, 0)
  ChangeUI(0, 0)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("What the heck...?\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>In any normal classroom, that's where a window should\nbe.\n<CLT>")
  AutoText("<CLT 4>But it looks like some kind of metal plate has been\nbolted over it.\n<CLT>")
  AutoText("<CLT 4>And if I were to knock on it...\n<CLT>")
  Sound(219, 100)
  ChangeUI(2, 0)
  AutoText("<CLT 23>*Bang bang*\n<CLT>")
  ChangeUI(0, 0)
  ChangeUI(2, 1)
  Speaker(0)
  AutoText("Yup. Definitely metal. Thick, too. Very solid.\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>Wait, that's not what matters here. More importantly,\nwhy are there metal plates over the windows?\n<CLT>")
  ChangeUI(1, 0)
  SetVar8(13, 1, 1)
  EvaluateFlag(13, 0, 0, 1, 6, 13, 1, 0, 1, 6, 13, 2, 0, 1)
  IfTrue()
  Goto(502)
  Goto(0)
  Label(502)
CheckObject(24)
  ChangeUI(15, 0)
  ChangeUI(0, 0)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("What the heck...?\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>In any normal classroom, that's where a window should\nbe.\n<CLT>")
  AutoText("<CLT 4>But it looks like some kind of metal plate has been\nbolted over it.\n<CLT>")
  AutoText("<CLT 4>And if I were to knock on it...\n<CLT>")
  Sound(219, 100)
  ChangeUI(2, 0)
  Speaker(31)
  AutoText("<CLT 23>*KONK KONK*\n<CLT>")
  ChangeUI(0, 0)
  ChangeUI(2, 1)
  Speaker(0)
  AutoText("Yup. Definitely metal. Thick, too. Very solid.\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>Wait, that's not what matters here.\n<CLT>")
  AutoText("<CLT 4>More importantly, why are there metal plates over the\nwindows?\n<CLT>")
  ChangeUI(1, 0)
  SetVar8(13, 1, 1)
  EvaluateFlag(13, 0, 0, 1, 6, 13, 1, 0, 1, 6, 13, 2, 0, 1)
  IfTrue()
  Goto(503)
  Goto(0)
  Label(503)
CheckObject(25)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>That's the desk I fell asleep on. I can still see a\nline of drool I must have left there.\n<CLT>")
  ChangeUI(0, 0)
  Speaker(0)
  AutoText("I'll have to clean that up later...\n")
  ChangeUI(0, 1)
  Speaker(0)
  TextStyle(4)
  Text("<CLT 4>Hey, what's that on the desk?\n<CLT>")
  WaitFrame()
  TextStyle(0)
  Animation(3000, 0, 0, 0, 0, 0, 1)
  WaitInput()
  ChangeUI(0, 0)
  Speaker(0)
  Sound(26, 100)
  ScreenFlash(255, 255, 255, 4, 0, 30, 255)
  AutoText("An orientation guide...?\n")
  AutoText("It's some kind of cheap-looking pamphlet. And there's\nsomething handwritten on it...\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>\"The next semester is about to start.\"\n<CLT>")
  AutoText("<CLT 4>\"Starting today, this school will be your entire\nworld.\"\n<CLT>")
  Animation(3000, 0, 0, 0, 0, 0, 2)
  ChangeUI(0, 0)
  Speaker(0)
  AutoText("What the hell? Is this someone's idea of a joke?\n")
  ChangeUI(1, 0)
  SetVar8(13, 2, 1)
  EvaluateFlag(13, 0, 0, 1, 6, 13, 1, 0, 1, 6, 13, 2, 0, 1)
  IfTrue()
  Goto(504)
  Goto(0)
  Label(504)
CheckObject(27)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>I'd better look around the classroom a little more\nbefore I head out...\n<CLT>")
  ChangeUI(1, 0)
CheckObject(254)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>I'd better look around the classroom a little more\nbefore I head out...\n<CLT>")
  ChangeUI(1, 0)
CheckObject(255)
Label(500)
Label(0)
ChangeUI(27, 0)
SetVar16(6, 0, 60)
ChangeUI(9, 1)
ChangeUI(0, 0)
ChangeUI(1, 1)
Speaker(0)
AutoText("Okay, let's see. So what might have happened is...\n")
ChangeUI(0, 1)
Speaker(0)
AutoText("<CLT 4>I got myself so wound up, I passed out in the main\nhall. And then someone carried me here...?\n<CLT>")
AutoText("<CLT 4>If that's true, it must mean...\n<CLT>")
Sound(26, 100)
ScreenFlash(255, 255, 255, 4, 0, 30, 255)
AutoText("<CLT 4>This is a classroom inside Hope's Peak.\n<CLT>")
ChangeUI(0, 0)
Speaker(0)
AutoText("But then if *that's* true...\n")
ChangeUI(0, 1)
Speaker(0)
AutoText("<CLT 4>That just raises more questions. This is all really\nstrange.\n<CLT>")
AutoText("<CLT 4>I mean, those metal plates covering the windows...\nIt's like it's a prison or something.\n<CLT>")
AutoText("<CLT 4>None of this makes any sense...\n<CLT>")
ChangeUI(0, 0)
Speaker(0)
AutoText("I should probably head back to the main hall.\n")
AutoText("It's already past the meeting time. There might be\nother students there now.\n")
ChangeUI(0, 1)
ChangeUI(2, 0)
ChangeUI(1, 1)
Speaker(31)
AutoText("<CLT 23>You can leave the classroom by pressing the <CLT><CLT 3>%CTRL_EXIT_RETURN%<CLT><CLT 23>.\n<CLT>")
ChangeUI(1, 0)
ChangeUI(2, 1)
SetVar8(0, 12, 1)
ChangeUI(16, 1)
Goto(505)
CheckCharacter(255)
CheckObject(20)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>There's a TV...\n<CLT>")
  AutoText("<CLT 4>The school *is* funded by the national government,\nso I guess it's not that weird to have TVs in here...\n<CLT>")
  AutoText("<CLT 4>Something feels...off. I wonder what it is...\n<CLT>")
  ChangeUI(1, 0)
CheckObject(21)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>Is that...a surveillance camera?\n<CLT>")
  AutoText("<CLT 4>It's a dangerous world we live in. I guess they have\nthese to keep weirdos from just wandering in.\n<CLT>")
  ChangeUI(1, 0)
CheckObject(22)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>Jeez, I can't believe it's already 8 o'clock.\n<CLT>")
  AutoText("<CLT 4>It was just after 7 when I first got here.\n<CLT>")
  AutoText("<CLT 4>Has it really been almost an hour since then...?\n<CLT>")
  ChangeUI(1, 0)
CheckObject(23)
  ChangeUI(15, 0)
  ChangeUI(0, 0)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("What the heck...?\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>In any normal classroom, that's where a window should\nbe.\n<CLT>")
  AutoText("<CLT 4>But it looks like some kind of metal plate has been\nbolted over it.\n<CLT>")
  AutoText("<CLT 4>And if I were to knock on it...\n<CLT>")
  Sound(219, 100)
  ChangeUI(2, 0)
  AutoText("<CLT 23>*Bang bang*\n<CLT>")
  ChangeUI(0, 0)
  ChangeUI(2, 1)
  Speaker(0)
  AutoText("Yup. Definitely metal. Thick, too. Very solid.\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>Wait, that's not what matters here. More importantly,\nwhy are there metal plates over the windows?\n<CLT>")
  ChangeUI(1, 0)
CheckObject(24)
  ChangeUI(15, 0)
  ChangeUI(0, 0)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("What the heck...?\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>In any normal classroom, that's where a window should\nbe.\n<CLT>")
  AutoText("<CLT 4>But it looks like some kind of metal plate has been\nbolted over it.\n<CLT>")
  AutoText("<CLT 4>And if I were to knock on it...\n<CLT>")
  Sound(219, 100)
  ChangeUI(2, 0)
  AutoText("<CLT 23>*Bang bang*\n<CLT>")
  ChangeUI(0, 0)
  ChangeUI(2, 1)
  Speaker(0)
  AutoText("Yup. Definitely metal. Thick, too. Very solid.\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>Wait, that's not what matters here. More importantly,\nwhy are there metal plates over the windows?\n<CLT>")
  ChangeUI(1, 0)
CheckObject(25)
  ChangeUI(15, 0)
  ChangeUI(0, 1)
  ChangeUI(1, 1)
  Speaker(0)
  AutoText("<CLT 4>That's the desk I fell asleep on. I can still see a\nline of drool I must have left there.\n<CLT>")
  ChangeUI(0, 0)
  Speaker(0)
  AutoText("I'll have to clean that up later...\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>Hey, what's that on the desk?\n<CLT>")
  Animation(3000, 0, 0, 0, 0, 0, 1)
  ChangeUI(0, 0)
  Speaker(0)
  AutoText("An orientation guide...?\n")
  AutoText("It's some kind of cheap-looking pamphlet. And there's\nsomething handwritten on it...\n")
  ChangeUI(0, 1)
  Speaker(0)
  AutoText("<CLT 4>\"The next semester is about to start.\"\n<CLT>")
  AutoText("<CLT 4>\"Starting today, this school will be your entire\nworld.\"\n<CLT>")
  Animation(3000, 0, 0, 0, 0, 0, 2)
  ChangeUI(0, 0)
  Speaker(0)
  AutoText("What the hell? Is this someone's idea of a joke?\n")
  ChangeUI(1, 0)
CheckObject(27)
  ChangeUI(15, 0)
  ChangeUI(2, 0)
  ChangeUI(1, 1)
  ChangeUI(18, 0)
  ChangeUI(18, 3)
  Goto(506)
  SetOption(1)
    Text("Yes\n")
    WaitFrame()
    ChangeUI(1, 0)
    ChangeUI(2, 1)
    Goto(1)
  SetOption(2)
    Text("No\n")
    WaitFrame()
    ChangeUI(1, 0)
    ChangeUI(2, 1)
  SetOption(18)
  SetOption(19)
    Speaker(31)
    TextStyle(23)
    Text("<CLT 23>Leave the area?\n<CLT>")
    WaitFrame()
    TextStyle(0)
  SetOption(255)
  Label(506)
CheckObject(254)
  ChangeUI(2, 0)
  ChangeUI(1, 1)
  ChangeUI(18, 0)
  ChangeUI(18, 3)
  Goto(507)
  SetOption(1)
    Text("Yes\n")
    WaitFrame()
    ChangeUI(1, 0)
    ChangeUI(2, 1)
    Goto(1)
  SetOption(2)
    Text("No\n")
    WaitFrame()
    ChangeUI(1, 0)
    ChangeUI(2, 1)
  SetOption(18)
  SetOption(19)
    Speaker(31)
    TextStyle(23)
    Text("<CLT 23>Leave the area?\n<CLT>")
    WaitFrame()
    TextStyle(0)
  SetOption(255)
  Label(507)
CheckObject(255)
Label(505)
Label(1)
SetVar16(8, 0, 2)
Sound(145, 100)
ScreenFade(1, 1, 24)
LoadScript(0, 3, 1)
StopScript()
StopScript()
`;
