// Hardcoded copy of workbench/linscript-exploration/e00_002_000.linscript (guinea pig for the Script Browser).
// String.raw keeps the literal \n sequences inside Text strings intact.
export const e00_002_000 = String.raw`ScreenFade(1, 0, 1)
SetUI(MovieBackground, Shown)
SetFlag(ObjectInvestigated, 32, False)
SetUI(TextboxOnly, Hidden)
SetUI(Investigate, Hidden)
SetVariable(0, 0, 0)
SetVariable(2, 0, 100)
SetVariable(3, 0, 100)
SetVariable(15, 0, 17)
SetVariable(8, 0, 0)
SetFlag(System, 12, False)
SetUI(BlackBackground, Hidden)
LoadMap(14, 0, 255)
SetUI(BustUp, Hidden)
ObjectState(26, 0, 0, 0, 0)
Music(7, 100, 0)
SetUI(HUD, Hidden)
SetUI(Name, Shown)
SetUI(Minimal, Hidden)
SetUI(BlackBackground, Shown)
ShowBackground(0, 1)
SetUI(BustUp, Shown)
ScreenFade(0, 1, 24)
SetUI(Thinking, Hidden)
SetUI(Textbox, Shown)
Speaker(Makoto)
Text("...\n")
Text("...\n")
Text("...\n")
Text("...Nng?\n")
SetUI(Textbox, Hidden)
ScreenFade(1, 1, 24)
ShowBackground(0, 3)
Animation(741, 0, 0, 0, 0, 0, 3)
ScreenFade(0, 1, 24)
Wait(60)
Animation(741, 0, 0, 0, 0, 0, 1)
Wait(60)
SetUI(Textbox, Shown)
Speaker(Makoto)
Voice(0, 99, 44, 100)
Text("Wh-What...?\n")
Text("Where am I?\n")
SetUI(Thinking, Shown)
Speaker(Makoto)
Text("<thought>I woke up with my head resting on top of a hard wooden\ndesk.\n</thought>")
Text("<thought>My body feels...heavy.\n</thought>")
Text("<thought>It's pretty normal for me to zonk off in the middle of\nsome boring class or whatever, but...\n</thought>")
Text("<thought>What was I doing asleep here just now?\n</thought>")
Text("<thought>This isn't a classroom I've ever been in before.\n</thought>")
SetUI(Thinking, Hidden)
Speaker(Makoto)
Text("What the heck is going on...?\n")
SetUI(Textbox, Hidden)
Music(255, 90, 0)
Wait(60)
ScreenFade(1, 1, 24)
Animation(741, 0, 0, 0, 0, 0, 255)
Music(32, 100, 60)
SetUI(BlackBackground, Hidden)
SetUI(CameraPan, Shown)
LoadMap(1, 1, 255)
Wait(30)
SetUI(CameraSubarea, Hidden)
SetUI(Thinking, Shown)
SetUI(Name, Hidden)
SetUI(Textbox, Shown)
Speaker(Blank)
Text("<system>Welcome to Hope's Peak Academy! Firstly, we'd like to\nexplain the basic controls.\n</system>")
Text("<system>You can use the %CTRL_INVESTIGATE_AIM% to adjust your </system><keyword>aim</keyword><system>.\n</system>")
Text("<system>If you aim at an object you can interact with,\nyou can press the </system><keyword>%CTRL_INTERACT%</keyword><system>...\n</system>")
Text("<system>And presto! You'll </system><keyword>investigate</keyword><system> that object.\n</system>")
Text("<style 23>Use the <style 0><style 3>%CTRL_ADJUST_VIEW%<style 0><style 23>\nto <style 3>adjust your viewpoint<style 0>.\n<style 0>")
Text("<system>%CTRL_INVESTIGATE_VIEW_ALT%\n</system>")
Text("<system>Why don't you try looking around the classroom?\n</system>")
SetUI(Textbox, Hidden)
SetUI(Name, Shown)
SetUI(Investigate, Shown)
Goto(500)
OnCharacter(255)
OnObject(20)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>There's a TV...\n</thought>")
  Text("<thought>The school *is* funded by the national government,\nso I guess it's not that weird to have TVs in here...\n</thought>")
  Text("<thought>Something feels...off. I wonder what it is...\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(21)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>Is that...a surveillance camera?\n</thought>")
  Text("<thought>It's a dangerous world we live in. I guess they have\nthese to keep weirdos from just wandering in.\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(22)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>Jeez, I can't believe it's already 8 o'clock.\n</thought>")
  Text("<thought>It was just after 7 when I first got here.\n</thought>")
  Text("<thought>Has it really been almost an hour since then...?\n</thought>")
  SetUI(Textbox, Hidden)
  SetFlag(ObjectInvestigated, 0, True)
  IfFlag(ObjectInvestigated, 0, !=, True, And, ObjectInvestigated, 1, !=, True, And, ObjectInvestigated, 2, !=, True)
  Then()
  Goto(501)
  Goto(0)
  Label(501)
OnObject(23)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Hidden)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("What the heck...?\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>In any normal classroom, that's where a window should\nbe.\n</thought>")
  Text("<thought>But it looks like some kind of metal plate has been\nbolted over it.\n</thought>")
  Text("<thought>And if I were to knock on it...\n</thought>")
  Sound(219, 100)
  SetUI(Name, Hidden)
  Text("<system>*Bang bang*\n</system>")
  SetUI(Thinking, Hidden)
  SetUI(Name, Shown)
  Speaker(Makoto)
  Text("Yup. Definitely metal. Thick, too. Very solid.\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>Wait, that's not what matters here. More importantly,\nwhy are there metal plates over the windows?\n</thought>")
  SetUI(Textbox, Hidden)
  SetFlag(ObjectInvestigated, 1, True)
  IfFlag(ObjectInvestigated, 0, !=, True, And, ObjectInvestigated, 1, !=, True, And, ObjectInvestigated, 2, !=, True)
  Then()
  Goto(502)
  Goto(0)
  Label(502)
OnObject(24)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Hidden)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("What the heck...?\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>In any normal classroom, that's where a window should\nbe.\n</thought>")
  Text("<thought>But it looks like some kind of metal plate has been\nbolted over it.\n</thought>")
  Text("<thought>And if I were to knock on it...\n</thought>")
  Sound(219, 100)
  SetUI(Name, Hidden)
  Speaker(Blank)
  Text("<system>*KONK KONK*\n</system>")
  SetUI(Thinking, Hidden)
  SetUI(Name, Shown)
  Speaker(Makoto)
  Text("Yup. Definitely metal. Thick, too. Very solid.\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>Wait, that's not what matters here.\n</thought>")
  Text("<thought>More importantly, why are there metal plates over the\nwindows?\n</thought>")
  SetUI(Textbox, Hidden)
  SetFlag(ObjectInvestigated, 1, True)
  IfFlag(ObjectInvestigated, 0, !=, True, And, ObjectInvestigated, 1, !=, True, And, ObjectInvestigated, 2, !=, True)
  Then()
  Goto(503)
  Goto(0)
  Label(503)
OnObject(25)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>That's the desk I fell asleep on. I can still see a\nline of drool I must have left there.\n</thought>")
  SetUI(Thinking, Hidden)
  Speaker(Makoto)
  Text("I'll have to clean that up later...\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  TextStyle(4)
  RawText("<thought>Hey, what's that on the desk?\n</thought>")
  WaitFrame()
  TextStyle(0)
  Animation(3000, 0, 0, 0, 0, 0, 1)
  WaitInput()
  SetUI(Thinking, Hidden)
  Speaker(Makoto)
  Sound(26, 100)
  ScreenFlash(255, 255, 255, 4, 0, 30, 255)
  Text("An orientation guide...?\n")
  Text("It's some kind of cheap-looking pamphlet. And there's\nsomething handwritten on it...\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>\"The next semester is about to start.\"\n</thought>")
  Text("<thought>\"Starting today, this school will be your entire\nworld.\"\n</thought>")
  Animation(3000, 0, 0, 0, 0, 0, 2)
  SetUI(Thinking, Hidden)
  Speaker(Makoto)
  Text("What the hell? Is this someone's idea of a joke?\n")
  SetUI(Textbox, Hidden)
  SetFlag(ObjectInvestigated, 2, True)
  IfFlag(ObjectInvestigated, 0, !=, True, And, ObjectInvestigated, 1, !=, True, And, ObjectInvestigated, 2, !=, True)
  Then()
  Goto(504)
  Goto(0)
  Label(504)
OnObject(27)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>I'd better look around the classroom a little more\nbefore I head out...\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(254)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>I'd better look around the classroom a little more\nbefore I head out...\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(255)
Label(500)
Label(0)
SetUI(CameraSubarea, Hidden)
Wait(60)
SetUI(BustUp, Shown)
SetUI(Thinking, Hidden)
SetUI(Textbox, Shown)
Speaker(Makoto)
Text("Okay, let's see. So what might have happened is...\n")
SetUI(Thinking, Shown)
Speaker(Makoto)
Text("<thought>I got myself so wound up, I passed out in the main\nhall. And then someone carried me here...?\n</thought>")
Text("<thought>If that's true, it must mean...\n</thought>")
Sound(26, 100)
ScreenFlash(255, 255, 255, 4, 0, 30, 255)
Text("<thought>This is a classroom inside Hope's Peak.\n</thought>")
SetUI(Thinking, Hidden)
Speaker(Makoto)
Text("But then if *that's* true...\n")
SetUI(Thinking, Shown)
Speaker(Makoto)
Text("<thought>That just raises more questions. This is all really\nstrange.\n</thought>")
Text("<thought>I mean, those metal plates covering the windows...\nIt's like it's a prison or something.\n</thought>")
Text("<thought>None of this makes any sense...\n</thought>")
SetUI(Thinking, Hidden)
Speaker(Makoto)
Text("I should probably head back to the main hall.\n")
Text("It's already past the meeting time. There might be\nother students there now.\n")
SetUI(Thinking, Shown)
SetUI(Name, Hidden)
SetUI(Textbox, Shown)
Speaker(Blank)
Text("<system>You can leave the classroom by pressing the </system><keyword>%CTRL_EXIT_RETURN%</keyword><system>.\n</system>")
SetUI(Textbox, Hidden)
SetUI(Name, Shown)
SetFlag(System, 12, True)
SetUI(Investigate, Shown)
Goto(505)
OnCharacter(255)
OnObject(20)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>There's a TV...\n</thought>")
  Text("<thought>The school *is* funded by the national government,\nso I guess it's not that weird to have TVs in here...\n</thought>")
  Text("<thought>Something feels...off. I wonder what it is...\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(21)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>Is that...a surveillance camera?\n</thought>")
  Text("<thought>It's a dangerous world we live in. I guess they have\nthese to keep weirdos from just wandering in.\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(22)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>Jeez, I can't believe it's already 8 o'clock.\n</thought>")
  Text("<thought>It was just after 7 when I first got here.\n</thought>")
  Text("<thought>Has it really been almost an hour since then...?\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(23)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Hidden)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("What the heck...?\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>In any normal classroom, that's where a window should\nbe.\n</thought>")
  Text("<thought>But it looks like some kind of metal plate has been\nbolted over it.\n</thought>")
  Text("<thought>And if I were to knock on it...\n</thought>")
  Sound(219, 100)
  SetUI(Name, Hidden)
  Text("<system>*Bang bang*\n</system>")
  SetUI(Thinking, Hidden)
  SetUI(Name, Shown)
  Speaker(Makoto)
  Text("Yup. Definitely metal. Thick, too. Very solid.\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>Wait, that's not what matters here. More importantly,\nwhy are there metal plates over the windows?\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(24)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Hidden)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("What the heck...?\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>In any normal classroom, that's where a window should\nbe.\n</thought>")
  Text("<thought>But it looks like some kind of metal plate has been\nbolted over it.\n</thought>")
  Text("<thought>And if I were to knock on it...\n</thought>")
  Sound(219, 100)
  SetUI(Name, Hidden)
  Text("<system>*Bang bang*\n</system>")
  SetUI(Thinking, Hidden)
  SetUI(Name, Shown)
  Speaker(Makoto)
  Text("Yup. Definitely metal. Thick, too. Very solid.\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>Wait, that's not what matters here. More importantly,\nwhy are there metal plates over the windows?\n</thought>")
  SetUI(Textbox, Hidden)
OnObject(25)
  SetUI(CameraLook, Hidden)
  SetUI(Thinking, Shown)
  SetUI(Textbox, Shown)
  Speaker(Makoto)
  Text("<thought>That's the desk I fell asleep on. I can still see a\nline of drool I must have left there.\n</thought>")
  SetUI(Thinking, Hidden)
  Speaker(Makoto)
  Text("I'll have to clean that up later...\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>Hey, what's that on the desk?\n</thought>")
  Animation(3000, 0, 0, 0, 0, 0, 1)
  SetUI(Thinking, Hidden)
  Speaker(Makoto)
  Text("An orientation guide...?\n")
  Text("It's some kind of cheap-looking pamphlet. And there's\nsomething handwritten on it...\n")
  SetUI(Thinking, Shown)
  Speaker(Makoto)
  Text("<thought>\"The next semester is about to start.\"\n</thought>")
  Text("<thought>\"Starting today, this school will be your entire\nworld.\"\n</thought>")
  Animation(3000, 0, 0, 0, 0, 0, 2)
  SetUI(Thinking, Hidden)
  Speaker(Makoto)
  Text("What the hell? Is this someone's idea of a joke?\n")
  SetUI(Textbox, Hidden)
OnObject(27)
  SetUI(CameraLook, Hidden)
  SetUI(Name, Hidden)
  SetUI(Textbox, Shown)
  SetUI(ChooseOption, Hidden)
  SetUI(ChooseOption, 3)
  Goto(506)
  SetOption(1)
    RawText("Yes\n")
    WaitFrame()
    SetUI(Textbox, Hidden)
    SetUI(Name, Shown)
    Goto(1)
  SetOption(2)
    RawText("No\n")
    WaitFrame()
    SetUI(Textbox, Hidden)
    SetUI(Name, Shown)
  SetOption(18)
  SetOption(19)
    Speaker(Blank)
    TextStyle(23)
    RawText("<system>Leave the area?\n</system>")
    WaitFrame()
    TextStyle(0)
  SetOption(255)
  Label(506)
OnObject(254)
  SetUI(Name, Hidden)
  SetUI(Textbox, Shown)
  SetUI(ChooseOption, Hidden)
  SetUI(ChooseOption, 3)
  Goto(507)
  SetOption(1)
    RawText("Yes\n")
    WaitFrame()
    SetUI(Textbox, Hidden)
    SetUI(Name, Shown)
    Goto(1)
  SetOption(2)
    RawText("No\n")
    WaitFrame()
    SetUI(Textbox, Hidden)
    SetUI(Name, Shown)
  SetOption(18)
  SetOption(19)
    Speaker(Blank)
    TextStyle(23)
    RawText("<system>Leave the area?\n</system>")
    WaitFrame()
    TextStyle(0)
  SetOption(255)
  Label(507)
OnObject(255)
Label(505)
Label(1)
SetVariable(8, 0, 2)
Sound(145, 100)
ScreenFade(1, 1, 24)
LoadScript(0, 3, 1)
StopScript()
StopScript()
`;
